from pathlib import Path
import os

MODEL_NAME = "google/gemma-2-2b-it"
DOLMA_URL = "https://olmo-data.org/dolma-v1_6/books/books-0000.json.gz"

USER = os.environ["USER"]
SCRATCH_ROOT = Path(f"/srv/scratch/{USER}")
RESOURCE_BASE = SCRATCH_ROOT / "sae-v1"
RESULT_BASE = SCRATCH_ROOT / "sae-v1-res"

DATA_CACHE_PATH = RESOURCE_BASE / "data_cache" / "books-0000.json.gz"
HF_BASE = RESOURCE_BASE / "hf"
INIT_STATS_DIR = RESOURCE_BASE / "init_stats"

SAE_RUN_NAME = os.environ.get("SAE_RUN_NAME", "jumprelu_sae")
SAE_RUN_STAMP = os.environ.get("SAE_RUN_STAMP", "manual")
SAE_RUN_DIR_ENV = os.environ.get("SAE_RUN_DIR")
if SAE_RUN_DIR_ENV:
    RUN_DIR = Path(SAE_RUN_DIR_ENV)
else:
    RUN_DIR = RESULT_BASE / f"{SAE_RUN_STAMP}-{SAE_RUN_NAME}"

HOOK_LAYER_INDEX = 12
MAX_SEQ_LEN = 256
MIN_TEXT_CHARS = 20

TEXT_BATCH_SIZE_PER_RANK = 32
TEXT_PREFETCH_BATCHES = 16
TEXT_PREFETCH_BACKEND = "process"

SAE_BATCH_SIZE = 4096
BUFFER_CAPACITY = 131072

TRAIN_STEPS = 10000
LOG_EVERY = 20
SAVE_EVERY = 1000

LATENT_DIM = 16384
LATENT_FACTOR = None

INIT_THRESHOLD = 5e-2
STE_BANDWIDTH = 1e-3
L0_COEFF = 5e-3

LR = 5e-5
ADAM_BETA1 = 0.0
ADAM_BETA2 = 0.999
ADAM_EPS = 1e-8

LR_WARMUP_STEPS = 500
LR_WARMUP_START_FACTOR = 0.1
L0_WARMUP_STEPS = 1000

MEAN_INIT_BATCHES = 64
TOKEN_STATS_BATCHES = 32
TOKEN_LENGTH_PROBE_MAX_LEN = 4096

TORCH_NUM_THREADS = 4
TORCH_NUM_INTEROP_THREADS = 1
TOKENIZERS_PARALLELISM = "true"
RAYON_NUM_THREADS = 4
PIN_MEMORY = True

SEED = 42
HTTP_TIMEOUT = 30
USER_AGENT = "Mozilla/5.0"

MODEL_TAG = MODEL_NAME.split("/")[-1].replace("-", "_").replace(".", "_")
OUTPUT_DIR = RUN_DIR / "checkpoints"
INIT_STATS_CACHE_PATH = INIT_STATS_DIR / f"init_stats_{MODEL_TAG}_layer{HOOK_LAYER_INDEX}_seq{MAX_SEQ_LEN}.pt"
